name: Run Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Create environment & install deps
      run: |
        conda create -n prepenv python=3.10 -y
        source activate prepenv
        conda install pandas numpy -y

    - name: Run preprocessing script
      run: |
        source activate prepenv
        python preprocessing/automate_Aprilia-Melani.py

    - name: Upload processed dataset
      uses: actions/upload-artifact@v3
      with:
        name: processed_dataset
        path: preprocessing/namadataset_preprocessing/
